# Generated by Django 5.2.4 on 2025-08-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='lesson_files/'),
        ),
    ]
