# Generated by Django 5.2.4 on 2025-08-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_thumbnail_alter_lesson_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text content'), ('video', 'Video content'), ('file', 'File content')], default='text', max_length=50),
        ),
    ]
