services:
  web_lms:
    build: .
    command: python manage.py runserver 0.0.0.0:1906
    volumes:
      - .:/app
    ports:
      - '1906:1906'
    env_file:
      - .env

  db:
    image: postgres:14.6-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
    - .env

  redis:
    image: redis:6-alpine
    ports:
    - "6379:6379"

  celery_worker:
    build: .
    command: celery -A lms worker -l info
    volumes:
    - .:/app
    depends_on:
    - redis

volumes:
  postgres_data: