# Generated by Django 5.2.4 on 2025-08-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberuser',
            name='wants_to_be_instructor',
            field=models.BooleanField(default=False, verbose_name='Instructor Request'),
        ),
    ]
