# Generated by Django 5.2.4 on 2025-08-22 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lesson_content_type'),
        ('users', '0005_memberuser_wants_to_be_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_completions', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Lesson Completions',
                'ordering': ['completed_at'],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
