# Generated by Django 5.2.4 on 2025-08-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLessonCompletion',
        ),
    ]
